### ISSUE TITLE
Titlerz ToDo

### ISSUE THREAD

**Issue by Alcheri** [Alcheri/Plugins#1]
*  [x] Enable/Disable plugin option for the channels the bot is in.
*  [x] Remove external library dependency pyshorteners.
*  [x] More code optimising.
*  [ ] Network detection for plugin customising.
*  [x] Add bad extension detection: ('.bmp', '.flv', '.m3u8')
*  [x] Add bad domain detection: (twitter.com, panoramio.com, kickass.to, tinypic.com, ebay.com, imgur.com, dropbox.com)
*  [x] Improve error catching and implement traceback.
*  [ ] Add option to pick colour output in channel.
*  [x] Backwards compatibility with Python 2
- [x] Fix bug: URLError: <urlopen error [Errno -5] No address associated with hostname>
- [x] Fix error: AttributeError 'NoneType'
